owner = {
    'A/S Norske Shell':'Basis',
    'A/S Norske Shell':'Petrojarl Knarr FPSO',
    'Aker BP ASA':'Alvheim FPSO',
    'Aker BP ASA':'Basis',
    'Aker BP ASA':'Bøyla ',
    'Aker BP ASA':'Ivar Aasen',
    'Aker BP ASA':'Jette',
    'Aker BP ASA':'Skarv FPSO',
    'Aker BP ASA':'Tambar',
    'Aker BP ASA':'Ula',
    'Aker BP ASA':'Ula D og P',
    'Aker BP ASA':'Valhall',
    'Aker BP ASA':'Valhall DP',
    'Aker BP ASA':'Valhall Flanke Nord',
    'Aker BP ASA':'Valhall Flanke Vest',
    'Aker BP ASA':'Valhall IP',
    'Aker BP ASA':'Valhall PH',
    'Aker BP ASA':'Valhallfeltet',
    'Aker Solutions':'Basis',
    'AKOFS Offshore Operations AS':'Akofs seafarer',
    'Archer':'Basis',
    'Baker Hughes Norge AS':'Basis',
    'Baker Hughes Norge AS, Archer AS, Halliburton AS, GE Oil & Gas og Schlumberger Norge AS':'Basis',
    'BG Norge AS':'Basis',
    'Bilfinger Industrier Norge AS':'Basis',
    'Blandfor Shipping Co. LTD':'Bideford Dolphin',
    'Capricorn Norge AS':'Lynghaug',
    'Centrica Resources (Norge) AS':'Basis',
    'Chrysaor Norge AS':'Petrojarl Varg FPSO',
    'ConocoPhillips Skandinavia AS':'Albuskjell 1/6-A',
    'ConocoPhillips Skandinavia AS':'Basis',
    'ConocoPhillips Skandinavia AS':'Ekofisk',
    'ConocoPhillips Skandinavia AS':'Ekofisk 2/4 B og K',
    'ConocoPhillips Skandinavia AS':'Ekofisk 2/4 J',
    'ConocoPhillips Skandinavia AS':'Ekofisk 2/4 J, M, Z, L, B, K',
    'ConocoPhillips Skandinavia AS':'Ekofisk 2/4 K',
    'ConocoPhillips Skandinavia AS':'Ekofisk 2/4 L',
    'ConocoPhillips Skandinavia AS':'Ekofisk 2/4-Alpha',
    'ConocoPhillips Skandinavia AS':'Ekofisk A',
    'ConocoPhillips Skandinavia AS':'Ekofisk B',
    'ConocoPhillips Skandinavia AS':'Ekofisk C',
    'ConocoPhillips Skandinavia AS':'Ekofisk C og J',
    'ConocoPhillips Skandinavia AS':'Ekofisk C, J, X',
    'ConocoPhillips Skandinavia AS':'Ekofisk J',
    'ConocoPhillips Skandinavia AS':'Ekofisk K og B',
    'ConocoPhillips Skandinavia AS':'Ekofisk L',
    'ConocoPhillips Skandinavia AS':'Ekofisk M og Z',
    'ConocoPhillips Skandinavia AS':'Ekofisk X',
    'ConocoPhillips Skandinavia AS':'Ekofisk Z',
    'ConocoPhillips Skandinavia AS':'Eldfisk',
    'ConocoPhillips Skandinavia AS':'Eldfisk 2/7',
    'ConocoPhillips Skandinavia AS':'Eldfisk 2/7 S',
    'ConocoPhillips Skandinavia AS':'Eldfisk 2/7-B, Embla 2/7-D og Eldfisk 2/7-S',
    'ConocoPhillips Skandinavia AS':'Eldfisk 2/7S',
    'ConocoPhillips Skandinavia AS':'Eldfisk 2/7-S',
    'ConocoPhillips Skandinavia AS':'Eldfisk A,FTP, B',
    'ConocoPhillips Skandinavia AS':'Eldfisk B ',
    'ConocoPhillips Skandinavia AS':'Eldfisk B og Ekofisk K',
    'ConocoPhillips Skandinavia AS':'Eldfisk S',
    'ConocoPhillips Skandinavia AS':'Embla 2/7-D',
    'ConocoPhillips Skandinavia AS, Equinor Energy AS, Lundin Norway AS, Odfjell Drilling AS, Transocean Norway Drilling AS, Maersk Drilling Norge AS, Halliburton, Schlumberger Norge, Baker Hughes':'Basis',
    'Coor Service Management':'Basis',
    'COSL Drilling Europe AS':'Basis',
    'COSL Drilling Europe AS':'COSL',
    'COSL Drilling Europe AS':'COSLInnovator',
    'COSL Drilling Europe AS':'COSLPioneer',
    'COSL Drilling Europe AS':'COSLPromoter',
    'COSL Drilling Europe AS':'COSLRiggmar',
    'Diamond Offshore Drilling LTD.':'Ocean Vanguard',
    'DNO Norge AS':'Oselvar og Trym',
    'Dolphin AS':'Borgland Dolphin',
    'Dolphin Drilling':'Basis',
    'E.on Ruhrgas Norge':'31/8-1 Breiflabb',
    'ENGIE E&P Norge AS':'Basis',
    'Eni Norge AS':'Basis',
    'Equinor Energy AS':'35/10-4S Stålull',
    'Equinor Energy AS':'7319/12-1 (Pingvin)',
    'Equinor Energy AS':'Aasta Hansteen',
    'Equinor Energy AS':'Askeladden',
    'Equinor Energy AS':'Askepott',
    'Equinor Energy AS':'Basis',
    'Equinor Energy AS':'',
    'Equinor Energy AS':'',
    'Equinor Energy AS':'Cat J-rigger',
    'Equinor Energy AS':'Gina Krog',
    'Equinor Energy AS':'Gina Krog FSO',
    'Equinor Energy AS':'Grane',
    'Equinor Energy AS':'Gudrun',
    'Equinor Energy AS':'Gullfaks',
    'Equinor Energy AS':'Gullfaks A',
    'Equinor Energy AS':'Gullfaks B',
    'Equinor Energy AS':'Gullfaks C',
    'Equinor Energy AS':'Gullfaks C og Oseberg B',
    'Equinor Energy AS':'Halten Nordland',
    'Equinor Energy AS':'Hammerfest LNG',
    'Equinor Energy AS':'Heidrun',
    'Equinor Energy AS':'Heimdal',
    'Equinor Energy AS':'Johan Castberg',
    'Equinor Energy AS':'Johan Sverdrup',
    'Equinor Energy AS':'Kayak',
    'Equinor Energy AS':'Kristin',
    'Equinor Energy AS':'Kvitebjørn',
    'Equinor Energy AS':'Letebrønn 6507/3-12',
    'Equinor Energy AS':'Martin Linge',
    'Equinor Energy AS':'Mongstad',
    'Equinor Energy AS':'Njord',
    'Equinor Energy AS':'Njord A',
    'Equinor Energy AS':'Njord B',
    'Equinor Energy AS':'Norne FPSO',
    'Equinor Energy AS':'Oseberg A',
    'Equinor Energy AS':'Oseberg C',
    'Equinor Energy AS':'Oseberg feltsenter',
    'Equinor Energy AS':'Oseberg H',
    'Equinor Energy AS':'Oseberg Sør',
    'Equinor Energy AS':'Oseberg Vestflanken 2',
    'Equinor Energy AS':'Oseberg Øst',
    'Equinor Energy AS':'Osebergfeltet',
    'Equinor Energy AS':'Skrugard',
    'Equinor Energy AS':'Sleipner A',
    'Equinor Energy AS':'Sleipner feltsenter',
    'Equinor Energy AS':'Sleipner Vest',
    'Equinor Energy AS':'Sleipner Øst',
    'Equinor Energy AS':'Snorre A',
    'Equinor Energy AS':'Snorre B',
    'Equinor Energy AS':'Snorre SEP',
    'Equinor Energy AS':'Snøhvit og Hammerfest',
    'Equinor Energy AS':'Statfjord',
    'Equinor Energy AS':'Statfjord A',
    'Equinor Energy AS':'Statfjord B',
    'Equinor Energy AS':'Statfjord C',
    'Equinor Energy AS':'Statfjord OLS B',
    'Equinor Energy AS':'Stureterminalen',
    'Equinor Energy AS':'Tjeldbergodden',
    'Equinor Energy AS':'Troll',
    'Equinor Energy AS':'Troll A',
    'Equinor Energy AS':'Troll B',
    'Equinor Energy AS':'Troll C',
    'Equinor Energy AS':'Valemon',
    'Equinor Energy AS':'Veslefikk A&B',
    'Equinor Energy AS':'Veslefrikk',
    'Equinor Energy AS':'Veslefrikk B',
    'Equinor Energy AS':'Veslefrikk, Huldra',
    'Equinor Energy AS':'Visund',
    'Equinor Energy AS':'Visund A',
    'Equinor Energy AS':'Volve',
    'Equinor Energy AS':'Åsgard',
    'Equinor Energy AS':'Åsgard A',
    'Equinor Energy AS':'Åsgard B',
    'Equinor Energy AS':'Åsgard subseakompresjon',
    'Equinor Energy AS, KCA Deutag':'Askepott, Oseberg H',
    'Equinor Energy AS, Transocean Norway Drilling AS':'Transocean Leader',
    'Esso':'Slagentangen',
    'ExxonMobil Exploration and Production Norway AS':'Basis',
    'Faroe Petroleum Norge AS':'Basis',
    'Floatel International AB':'Basis',
    'Floatel International AB':'Floatel Endurance',
    'Floatel International AB':'Floatel Superior',
    'Gassco AS':'B11',
    'Gassco AS':'Draupner ',
    'Gassco AS':'Kollsnes',
    'Gassco AS':'Kårstø',
    'Gassco AS':'Nyhamna',
    'Gassco AS':'Statpipe',
    'GDF SUEZ E&P Norge AS':'Basis',
    'Halliburton Geophysical Services':'Basis',
    'Halliburton Geophysical Services':'',
    'Island Offshore III AS':'Basis',
    'Island Offshore III AS':'Island Constructor',
    'Island Offshore III AS':'Island Frontier',
    'Island Offshore III AS':'Island Wellserver',
    'KCA Deutag':'Basis',
    'Lundin Norway AS':'Basis',
    'Lundin Norway AS':'Brynhild',
    'Lundin Norway AS':'Brønn 7220/11-T-5 S Alta',
    'Lundin Norway AS':'Edvard Grieg',
    'Lundin Norway AS':'Luno II',
    'Lundin Norway AS':'Solveig',
    'Maersk Drilling Norge AS':'Basis',
    'Maersk Drilling Norge AS':'Maersk Integrator',
    'Maersk Drilling Norge AS':'Maersk Interceptor',
    'Maersk Drilling Norge AS':'Maersk Intrepid',
    'Maersk Drilling Norge AS':'Maersk Invincible',
    'Maersk Drilling Norge AS':'Maersk Reacher',
    'Maersk Olie og Gass A/S':'Maersk Inspirer',
    'Many':'Basis',
    'MOL Norge AS':'Basis',
    'MOL Norge AS':'',
    'MOL Norge AS':'Letebrønn 2/6-6 S Oppdal/Driva',
    'Mærsk Contractors':'Maersk Gallant',
    'Mærsk Contractors':'Maersk Guardian',
    'Neptune Energy Norge AS':'Basis',
    'Neptune Energy Norge AS':'Fenja',
    'Neptune Energy Norge AS':'Fenja og Njord',
    'Neptune Energy Norge AS':'Gjøa',
    'Norisol Norge AS ':'Basis',
    'Norsk Yrkesdykkerskole':'Basis',
    'North Atlantic Norway Ltd':'Basis',
    'North Atlantic Norway Ltd':'West Alpha',
    'North Atlantic Norway Ltd':'West Elara',
    'North Atlantic Norway Ltd':'West Epsilon',
    'North Atlantic Norway Ltd':'West Hercules',
    'North Atlantic Norway Ltd':'West Linus',
    'North Atlantic Norway Ltd':'West Mira',
    'North Atlantic Norway Ltd':'West Phoenix',
    'North Atlantic Norway Ltd':'West Venture',
    'North Atlantic Norway Ltd':'West Bollsta',
    'Ocean Rig ASA':'Leiv Eiriksson',
    'Odfjell Drilling AS':'Basis',
    'Odfjell Drilling AS':'Deepsea Atlantic',
    'Odfjell Drilling AS':'Deepsea Bergen',
    'Odfjell Drilling AS':'Deepsea Nordkapp',
    'Odfjell Drilling AS':'Deepsea Stavanger',
    'Odfjell Drilling AS':'Deepsea Yantai',
    'Odfjell Drilling AS':'Island Innovator',
    'OKEA ASA':'Draugen',
    'OMV (Norge) AS':'Basis',
    'OSM Ship Management AS':'Haven',
    'Pandion Energy AS':'Basis',
    'PGNiG Upstream Norway AS':'6507/5-9 S (Shrek)',
    'Point Resources AS':'Basis',
    'Premier Oil Norge AS':'Basis',
    'Prosafe Offshore Limited':'Basis',
    'Prosafe Offshore Limited':'Safe Boreas',
    'Prosafe Offshore Limited':'Safe Scandinavia',
    'Prosafe Offshore Limited':'Safe Zephyrus',
    'Repsol Norge AS':'Basis',
    'Repsol Norge AS':'Gyda',
    'Repsol Norge AS':'Yme',
    'Rowan Companies Inc':'Basis',
    'Rowan Companies Inc':'Rowan Gorilla VI',
    'Rowan Companies Inc':'Rowan Norway',
    'Rowan Companies Inc':'Rowan Stavanger',
    'Rowan Companies Inc':'Rowan Viking',
    'RWE Dea Norge AS':'6611/1-1 Toutatis',
    'Saipem (UK) Ltd':'Basis',
    'Saipem (UK) Ltd':'Scarabeo 8',
    'Schlumberger Norge':'Basis',
    'Seadrill Offshore AS':'Basis',
    'Sodexo Remote Sites Norway AS':'Basis',
    'Songa Offshore ASA':'Songa Dee',
    'Songa Offshore ASA':'Songa Trym',
    'Spirit Energy Norway AS':'Oda',
    'Stena Drilling Limited':'Basis',
    'Stena Drilling Limited':'Stena Don',
    'Teekay':'Basis',
    'Total E&P Norge AS':'Basis',
    'Transocean Norway Drilling AS':'Basis',
    'Transocean Norway Drilling AS':'Cat D-rigger',
    'Transocean Norway Drilling AS':'Songa Enabler',
    'Transocean Norway Drilling AS':'Songa Encourage',
    'Transocean Norway Drilling AS':'Transocean',
    'Transocean Norway Drilling AS':'Transocean Arctic',
    'Transocean Norway Drilling AS':'Transocean Barents',
    'Transocean Norway Drilling AS':'Transocean Endurance',
    'Transocean Norway Drilling AS':'Transocean Leader',
    'Transocean Norway Drilling AS':'Transocean Norge',
    'Transocean Norway Drilling AS':'Transocean Spitsbergen',
    'Transocean Services AS':'Songa Endurance',
    'Transocean Services AS':'Songa Equinox',
    'VNG Norge AS':'Basis',
    'Vår Energi AS':'Balder',
    'Vår Energi AS':'Balder- og Ringhorne',
    'Vår Energi AS':'Balder, Jotun A, Jotun B og Ringhorne',
    'Vår Energi AS':'Goliat FPSO',
    'Vår Energi AS':'Jotun',
    'Vår Energi AS':'Jotun A',
    'Vår Energi AS':'Jotun B',
    'Vår Energi AS':'Ringhorne',
    'Wellesley Petroleum AS':'35/4-U-1 Songesand',
    'Wintershall Dea Norge AS':'Basis',
    'Wintershall Dea Norge AS':'',
    'Wintershall Dea Norge AS':'',
    'Wintershall Dea Norge AS':'Brage',
    'Wintershall Dea Norge AS':'',
    'Wintershall Dea Norge AS':'Maria',
    'Wood':'Basis',
}